(()=>{
const euro=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const num=new Intl.NumberFormat('it-IT');
const params=new URLSearchParams(location.search);let partner=(params.get('partner')||params.get('azienda')||params.get('nome')||'').trim().replace(/[<>]/g,'').slice(0,80);
if(partner){document.title=`Timeless Puglia × ${partner}`;document.querySelector('meta[name="description"]').content=`Una proposta territoriale Timeless Puglia pensata per ${partner}.`;document.querySelector('[data-personal-eyebrow]').textContent=`Una proposta territoriale per ${partner}`;document.querySelector('[data-personal-hero]').textContent=`Timeless mette a disposizione tecnologia, brand, revenue management e assistenza continua. ${partner} porta presenza, velocità e conoscenza reale del territorio.`;document.querySelector('[data-personal-tag] span').textContent=`Timeless Puglia × ${partner}`;document.querySelectorAll('[data-partner]').forEach(el=>el.textContent=partner);document.querySelector('[data-calc-partner]').textContent=`Scenario annuale per ${partner}, su un singolo immobile`;document.querySelector('[data-personal-closing]').textContent=`La bellezza ci ha dato il punto di partenza. ${partner} può aiutarci a darle scala.`;document.querySelector('[data-personal-badge]').textContent=`Una visione condivisa con ${partner}`;}
const b=document.getElementById('bookings'),c=document.getElementById('commissions');
function calc(){const bookings=+b.value,commissions=+c.value;const cleaning=bookings*60;const maintenance=commissions*.10;const operating=(commissions-maintenance)*.30;const total=cleaning+maintenance+operating;document.getElementById('bookingsOut').textContent=num.format(bookings);document.getElementById('commissionsOut').textContent=euro.format(commissions);document.getElementById('operatingFee').textContent=euro.format(operating);document.getElementById('cleaningFee').textContent=euro.format(cleaning);document.getElementById('maintenanceFee').textContent=euro.format(maintenance);document.getElementById('partnerTotal').textContent=euro.format(total);document.getElementById('monthlyTotal').textContent=euro.format(total/12);}
b.addEventListener('input',calc);c.addEventListener('input',calc);calc();
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const progress=document.querySelector('.progress i'),hero=document.querySelector('.hero-bg');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`;if(hero&&scrollY<innerHeight*1.1)hero.style.transform=`translate3d(0,${scrollY*.08}px,0) scale(1.02)`;},{passive:true});
})();